name: Backend CI

on:
  push:
    paths:
      - 'fitness-tracker-backend/**'
  pull_request:
    paths:
      - 'fitness-tracker-backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: fitness-tracker-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests (optional)
        run: npm test || echo "No tests yet"
